name: LWLibDemo
author: LW-MrWU

website: http://www.gameclub.vip
description: LWLibDemo is LWLib demo

main: com.gameclub.demo.MainPlugin
version: 1.0
api-version: 1.16

softdepend: [LWLib]
load: startup
database: false
commands:
  lld:
    description: LWLibDemo prefix
    usage: /<command> help
